version: "3.9"

services:
  nutrition-tracker:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "file:/app/data/dev.db"
    volumes:
      - ./prisma:/app/data
      - ./certs:/app/certs
    restart: unless-stopped
